---
default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: fix-encoding-pragma

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - "--skip=B101"
          - "-x *test.py,test*.py"

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy boto3_post_conditions
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - "--strict"
